# .github/workflows/convert-to-pdf.yml

name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - '**.md'
      - '5.-start-coding/**.md'
      - 'ilova/**.md'
      - '.gitbook/assets/**'

jobs:
  copy_files:
    name: Aggregate all md files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create destination directory
        run: mkdir -p docs # 복사될 디렉토리 생성

      - name: Copy specific files
        run: | # 루트부터 하위의 모든 md 파일들을 찾아 docs로 덮어씌기
          find / -type f -name "*.md" -exec cp -f {} docs \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: copied-files
          path: docs/ # 복사된 파일들이 포함된 디렉토리 업로드
          
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    needs: copy_files
    steps:
      - uses: actions/checkout@v4
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: docs 
          output_dir: pdfs
          images_dir: .gitbook/assets
          # for example <img src="./images/file-name.png">
          # image_import: ./images
          # Default is true, can set to false to only get PDF files
          build_html: false
      - uses: actions/upload-artifact@v3
        with:
          name: docs
          path: pdfs
